/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author Usuario
 */
public class TextingconX extends javax.swing.JFrame {

    /**
     * Creates new form TextingconX
     */
    public TextingconX() {
        initComponents();
        //hay una interface llamada networking para hacer lo de NIC
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        panelsystem = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        labelversion = new javax.swing.JLabel();
        labelfamilia = new javax.swing.JLabel();
        labelfisicainter = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelfisicatotal = new javax.swing.JLabel();
        panelcpu = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelmarcaCpu = new javax.swing.JLabel();
        labelmodeloCpu = new javax.swing.JLabel();
        labelarquitectura = new javax.swing.JLabel();
        labelnucleosfisicos = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jLabel32 = new javax.swing.JLabel();
        labeltemperaturaCpu = new javax.swing.JLabel();
        labelvoltajeCpu = new javax.swing.JLabel();
        labelusoCpu = new javax.swing.JLabel();
        labelnucleoslogicos = new javax.swing.JLabel();
        panelMotherboard = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        labelmarcaMother = new javax.swing.JLabel();
        labelmodeloMother = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setText("Memoria fisica en uso :");

        jLabel31.setText("Memoria de intercambio en uso :");

        labelversion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelversion.setText("jLabel16");
        labelversion.setToolTipText("");

        labelfamilia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelfamilia.setText("jLabel17");

        labelfisicainter.setText("jLabel18");

        jLabel2.setText("Familia del SO :");

        jLabel3.setText("Versión del SO :");

        jLabel4.setText("Memoria fisica total :");

        jLabel5.setText("Memoria de intercambio total :");

        labelfisicatotal.setText("jLabel19");

        javax.swing.GroupLayout panelsystemLayout = new javax.swing.GroupLayout(panelsystem);
        panelsystem.setLayout(panelsystemLayout);
        panelsystemLayout.setHorizontalGroup(
            panelsystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsystemLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelsystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelsystemLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(91, 91, 91)
                        .addComponent(labelfamilia))
                    .addGroup(panelsystemLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(88, 88, 88)
                        .addComponent(labelversion))
                    .addGroup(panelsystemLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(65, 65, 65)
                        .addComponent(labelfisicatotal)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel30))
                    .addGroup(panelsystemLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(labelfisicainter)
                        .addGap(101, 101, 101)
                        .addComponent(jLabel31)))
                .addGap(104, 104, 104))
        );
        panelsystemLayout.setVerticalGroup(
            panelsystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsystemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelsystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(labelfamilia))
                .addGap(6, 6, 6)
                .addGroup(panelsystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(labelversion))
                .addGap(6, 6, 6)
                .addGroup(panelsystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(labelfisicatotal)
                    .addComponent(jLabel30))
                .addGap(6, 6, 6)
                .addGroup(panelsystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(labelfisicainter)
                    .addComponent(jLabel31))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        labelversion.getAccessibleContext().setAccessibleName("jFamilia");

        getContentPane().add(panelsystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 610, 100));

        jLabel7.setText("Marca :");

        jLabel8.setText("Modelo :");

        jLabel9.setText("Arquitectura :");

        jLabel10.setText("Cantidad de nucleos fisicos :");

        jLabel11.setText("Cantidad de nucleos logicos :");

        labelmarcaCpu.setText("jLabel20");

        labelmodeloCpu.setText("jLabel21");

        labelarquitectura.setText("jLabel22");

        labelnucleosfisicos.setText("jLabel23");

        jLabel27.setText("Temperatura del CPU :");

        jLabel28.setText("Voltaje del CPU :");

        jLabel29.setText("Uso del CPU :");

        jLabel32.setText("Frecuencia de actualizacion:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addGap(6, 6, 6)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labeltemperaturaCpu.setText("jLabel15");

        labelvoltajeCpu.setText("jLabel33");

        labelusoCpu.setText("jLabel34");

        labelnucleoslogicos.setText("jLabel24");

        javax.swing.GroupLayout panelcpuLayout = new javax.swing.GroupLayout(panelcpu);
        panelcpu.setLayout(panelcpuLayout);
        panelcpuLayout.setHorizontalGroup(
            panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcpuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(24, 24, 24)
                .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelnucleoslogicos)
                    .addGroup(panelcpuLayout.createSequentialGroup()
                        .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelcpuLayout.createSequentialGroup()
                                .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelmarcaCpu)
                                    .addComponent(labelmodeloCpu))
                                .addGap(64, 64, 64)
                                .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)))
                            .addGroup(panelcpuLayout.createSequentialGroup()
                                .addComponent(labelarquitectura)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel29)))
                        .addGap(45, 45, 45)
                        .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelusoCpu)
                            .addComponent(labelvoltajeCpu)
                            .addComponent(labeltemperaturaCpu)))
                    .addComponent(labelnucleosfisicos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelcpuLayout.setVerticalGroup(
            panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelcpuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcpuLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel8))
                    .addGroup(panelcpuLayout.createSequentialGroup()
                        .addComponent(labelmarcaCpu)
                        .addGap(6, 6, 6)
                        .addComponent(labelmodeloCpu))
                    .addGroup(panelcpuLayout.createSequentialGroup()
                        .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(labeltemperaturaCpu))
                        .addGap(6, 6, 6)
                        .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(labelvoltajeCpu))))
                .addGap(6, 6, 6)
                .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelcpuLayout.createSequentialGroup()
                        .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(labelusoCpu)
                            .addComponent(labelarquitectura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(labelnucleosfisicos)))
                    .addComponent(jLabel29))
                .addGap(6, 6, 6)
                .addGroup(panelcpuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(labelnucleoslogicos))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelcpuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelcpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 710, 120));

        jLabel13.setText("Marca :");

        jLabel14.setText("Modelo :");

        jLabel25.setText("jLabel25");

        labelmarcaMother.setText("jLabel15");

        labelmodeloMother.setText("jLabel15");

        javax.swing.GroupLayout panelMotherboardLayout = new javax.swing.GroupLayout(panelMotherboard);
        panelMotherboard.setLayout(panelMotherboardLayout);
        panelMotherboardLayout.setHorizontalGroup(
            panelMotherboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotherboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMotherboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGroup(panelMotherboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMotherboardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addContainerGap(66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMotherboardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelMotherboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelmodeloMother, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelmarcaMother, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        panelMotherboardLayout.setVerticalGroup(
            panelMotherboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMotherboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMotherboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(labelmarcaMother))
                .addGap(6, 6, 6)
                .addGroup(panelMotherboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(labelmodeloMother))
                .addGap(23, 23, 23)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelMotherboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 220, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Cpu");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 80, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Motherboard");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 26));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextingconX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextingconX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextingconX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextingconX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextingconX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel labelarquitectura;
    private javax.swing.JLabel labelfamilia;
    private javax.swing.JLabel labelfisicainter;
    private javax.swing.JLabel labelfisicatotal;
    private javax.swing.JLabel labelmarcaCpu;
    private javax.swing.JLabel labelmarcaMother;
    private javax.swing.JLabel labelmodeloCpu;
    private javax.swing.JLabel labelmodeloMother;
    private javax.swing.JLabel labelnucleosfisicos;
    private javax.swing.JLabel labelnucleoslogicos;
    private javax.swing.JLabel labeltemperaturaCpu;
    private javax.swing.JLabel labelusoCpu;
    private javax.swing.JLabel labelversion;
    private javax.swing.JLabel labelvoltajeCpu;
    private javax.swing.JPanel panelMotherboard;
    private javax.swing.JPanel panelcpu;
    private javax.swing.JPanel panelsystem;
    // End of variables declaration//GEN-END:variables
}
